/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/Program Files (x86)/eclipse-SDK-3.8.2-win32/TI/grace_3_00_03_66/packages/ti/mcu/msp430/csl/interrupt_vectors/InterruptVectors_init.xdt
 */
#include <msp430.h>
#include "_Grace.h"

/* USER CODE START (section: InterruptVectors_init_c_prologue) */
#include "../../i2c.h"
#include "../../uart.h"

/* USER CODE END (section: InterruptVectors_init_c_prologue) */

/*
 *  ======== InterruptVectors_graceInit ========
 */
void InterruptVectors_graceInit(void)
{
}


/* Interrupt Function Prototypes */


/*
 *  ======== USCI A0/B0 TX Interrupt Handler Generation ========
 *
 * Here are several important notes on using USCI_A0/B0 TX interrupt Handler:
 * 1. User could use the following code as a template to service the interrupt
 *    handler. Just simply copy and paste it into your user definable code
 *    section.
 *  For UART and SPI configuration:

    if (IFG2 & UCA0TXIFG) {

    }
    else if (IFG2 & UCB0TXIFG) {

    }

 *  For I2C configuration:
    if (IFG2 & UCA0/B0TXIFG) {

    }
    else if (IFG2 & UCA0/B0RXIFG) {

    }


 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 */
#pragma vector=USCIAB0TX_VECTOR
__interrupt void USCI0TX_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI0TX_ISR_HOOK) */



	if ((IFG2 & UCA0TXIFG)) {			//Detecta fin de transmisión UART
		IE2 &= ~UCA0TXIE;				//Deshabilita la Int para que no reentre
		IFG2&= ~UCA0TXIFG;		//Limpia la interrupción, mejor la limpio al enviar// mejor si, por que si no I2C entra aquí
		LPM0_EXIT;							//Despierta y sigue con el resto del código
	}


	if ((IFG2 & UCB0TXIFG)) {		//FUe el I2C en modo transmisión?
		//		  IE2 &= ~UCB0TXIE;			//Deshabilita la Int para que no reentre
		IFG2&= ~UCB0TXIFG;		//Limpia la interrupción, mejor la limpio al enviar// mejor si, por que si no I2C entra aquí
		rutildeTX();
	}

	if (IFG2 & UCB0RXIFG) {				//Curioso pero la TX ISR atiende las recepciones para i2c
		//		  IE2 &= ~UCB0RXIE;					//Deshabilita la Int para que no reentre
		IFG2&= ~UCB0RXIFG;			//Limpia la interrupción, mejor la limpio al enviar// mejor si, por que si no I2C entra aquí
		if(rutildeRX()){
			LPM0_EXIT;							//Despierta y sigue con el resto del código
		}
	}



	/* USER CODE END (section: USCI0TX_ISR_HOOK) */
}

/*
 *  ======== USCI A0/B0 RX Interrupt Handler Generation ========
 *
 * Here are several important notes on using USCI_A0/B0 RX interrupt Handler:
 * 1. User could use the following code as a template to service the interrupt
 *    handler. Just simply copy and paste it into your user definable code
 *    section.
 *  For UART and SPI configuration:

    if (IFG2 & UCA0RXIFG) {

    }
    else if (IFG2 & UCB0RXIFG) {

    }

*  For I2C configuration:
    if (UCB0STAT & UCSTTIFG) {

    }
    else if (UCB0STAT & UCSTPIFG) {

    }
    else if (UCB0STAT & UCNACKIFG) {

    }
    else if (UCB0STAT & UCALIFG) {

    }

 * 2. User could also exit from low power mode and continue with main
 *    program execution by using the following instruction before exiting
 *    this interrupt handler.
 *
 *    __bic_SR_register_on_exit(LPMx_bits);
 */
#pragma vector=USCIAB0RX_VECTOR
__interrupt void USCI0RX_ISR_HOOK(void)
{
    /* USER CODE START (section: USCI0RX_ISR_HOOK) */

	if (IFG2 & UCA0RXIFG) {									//UART
		buffer_escritura_UART[0]=UCA0RXBUF;
		IE2 &= ~UCA0RXIE;										//Deshabilita la Int para que no reentre
		IFG2&= ~UCA0RXIFG;									//Limpia la interrupción
		LPM0_EXIT;
	}

	if (UCB0STAT & UCNACKIFG){            		// I2C no agarra la onda noAKL
		UCB0CTL1 |= UCTXSTP;							//termina la transmisión o recepción
		UCB0STAT &= ~UCNACKIFG;					//limpia Int
	}

	/* USER CODE END (section: USCI0RX_ISR_HOOK) */
}
